NST = 'nst'
PDST = 'pdst'
JMWST = 'jmwst'
SPDST = 'spdst'
DENSE = 'dense'
TRUE = 'true'
FALSE = 'false'
MNIST = 'mnist'
CIFAR10 = 'cifar10'
CIFAR100 = 'cifar100'
TINY = 'tinyimagenet'
RESNET18 = 'resnet18'
true_false = [TRUE, FALSE]
experiment_choices = [NST, DENSE, PDST, SPDST, JMWST]
model_choices = [RESNET18, 'lenet', 'mnistnet', 'cnn', 'resnet18_tiny', 'resnet34']
